### ISSUE TITLE
no replset config has been received

### ISSUE THREAD

**Issue by rysinal** [OT-CONTAINER-KIT/mongodb-operator#59]
```
---
apiVersion: opstreelabs.in/v1alpha1
kind: MongoDBCluster
metadata:
  name: mongodb-demo
  namespace: mongodb-system
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/mongo:v5.0.6
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 2
        memory: 1024Mi
      limits:
        cpu: 2
        memory: 4Gi
  storage:
    accessModes: ["ReadWriteOnce"]
    storageSize: 100Gi
    storageClass: nfs
  mongoDBSecurity:
    mongoDBAdminUser: admin
    secretRef:
      name: mongodb-cluster-secret
      key: demo-admin-password
  mongoDBMonitoring:
    enableExporter: true
    image: bitnami/mongodb-exporter:0.11.2-debian-10-r382
    imagePullPolicy: IfNotPresent
  mongoDBAdditionalConfig: mongo-demo-config # name of configmap

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-demo-config
  namespace: mongodb-system
data:
  mongo.yaml: |
    net:
      bindIp: 0.0.0.0
      port: 27017

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-cluster-secret
  namespace: mongodb-system
type: Opaque
stringData:
  demo-admin-password: 'abc123de2mo'
```

```
mongo -u $MONGO_ROOT_USERNAME -p $MONGO_ROOT_PASSWORD --eval "db.adminCommand( { replSetGetStatus: 1 } )"
```

```
> use admin
switched to db admin
> db.auth('admin','abc123de2mo')
1
> rs.status()
{
        "ok" : 0,
        "errmsg" : "no replset config has been received",
        "code" : 94,
        "codeName" : "NotYetInitialized"
}
>
```

but i got an error msg from operator like this

```
2022-07-04T07:49:17.930Z	ERROR	controller_mongo	Unable to create MongoDB cluster	{"Namespace": "mongodb-system", "Name": "mongodb-demo", "Resource Type": "MongoDB Cluster Setup", "error": "connection() error occured during connection handshake: auth error: unable to authenticate using mechanism \"SCRAM-SHA-256\": (AuthenticationFailed) Authentication failed."}

 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler

 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:311

 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem

 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:266

 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2

 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227

 2022-07-04T07:49:17.930Z	ERROR	controller.mongodbcluster	Reconciler error	{"reconciler group": "opstreelabs.in", "reconciler kind": "MongoDBCluster", "name": "mongodb-demo", "namespace": "mongodb-system", "error": "connection() error occured during connection handshake: auth error: unable to authenticate using mechanism \"SCRAM-SHA-256\": (AuthenticationFailed) Authentication failed."}

 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2

 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227
```
